# Generated by Django 4.0.1 on 2022-04-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
