# Generated by Django 4.0.1 on 2022-04-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_subsidiary_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsidiary',
            options={'verbose_name': 'Subsidiary', 'verbose_name_plural': 'Subsidiarys'},
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name_subsidiary'),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name_Station')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.subsidiary', verbose_name='Subsidiary')),
            ],
        ),
    ]
